# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-head}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Eley"]
  s.date = %q{2010-05-20}
  s.description = %q{Sinatra::Head provides class methods and helpers for dynamically controlling the fields in your <HEAD> element that are usually preset in your layout: the page title, stylesheet and javascript assets, etc.  Asset lists are inherited throughout superclasses, subclasses, and within action methods, and basic asset path management is supported.}
  s.email = %q{sfeley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.markdown",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.markdown",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/sinatra/head.rb",
     "lib/sinatra/head/data_helpers.rb",
     "lib/sinatra/head/tag_helpers.rb",
     "sinatra-head.gemspec",
     "spec/sinatra/head_spec.rb",
     "spec/sinatra/javascripts_spec.rb",
     "spec/sinatra/stylesheet_spec.rb",
     "spec/sinatra/title_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/dummy_app.rb"
  ]
  s.homepage = %q{http://github.com/SFEley/sinatra-head}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Sinatra extension that gets inside your <HEAD>.}
  s.test_files = [
    "spec/sinatra/head_spec.rb",
     "spec/sinatra/javascripts_spec.rb",
     "spec/sinatra/stylesheet_spec.rb",
     "spec/sinatra/title_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/dummy_app.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<haml>, [">= 3"])
      s.add_development_dependency(%q<capybara>, [">= 0.3.8"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<capybara>, [">= 0.3.8"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<capybara>, [">= 0.3.8"])
  end
end

